apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-sample
spec:
  instances: 3
  imageName: quay.io/enterprisedb/postgresql:16.4
  minSyncReplicas: 1
  maxSyncReplicas: 1
  enableSuperuserAccess: true

  replicationSlots:
    highAvailability:
      enabled: true

  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all

  storage:
    size: 1Gi

  walStorage:
    resizeInUseVolumes: true
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  backup:
    #target: "prefer-standby"
    barmanObjectStore:
      destinationPath: "s3://sergio1-bucket/"
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-creds
          key: ACCESS_SECRET_KEY
        sessionToken:
          name: minio-creds
          key: ACCESS_SESSION_TOKEN
      data:
        immediateCheckpoint: true
      wal:
        compression: gzip
        maxParallel: 8
        encryption: AES256
    retentionPolicy: "1d"

  managed:
    services:
      #disabledDefaultServices: ["ro", "r"]
      additional:
      - selectorType: rw
        serviceTemplate:
          metadata:
            name: cluster-sample-rw-lb
          spec:
            type: LoadBalancer

