apiVersion: v1
data:
  #key: $(echo -n "Thisismypassword01" | base64)
  key: VGhpc2lzbXlwYXNzd29yZDAx
kind: Secret
metadata:
  name: tde-key
---
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: ${cluster_name}-tde
spec:
  instances: 1
  imageName: $epas_image
  imagePullSecrets:
  - name: postgresql-operator-pull-secret

  enableSuperuserAccess: true
  postgresql:
    epas:
      tde:
        enabled: true
        secretKeyRef:
          name: tde-key
          key: key

  storage:
    size: $epas_storage

  bootstrap:
    initdb:
      redwood: true
