apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-sample-tde
  namespace: openshift-operators
spec:
  logLevel: info
  startDelay: 30
  stopDelay: 30
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  backup:
    target: prefer-standby
  enableSuperuserAccess: true
  monitoring:
    disableDefaultQueries: false
    enablePodMonitor: false
  postgresGID: 26
  replicationSlots:
    highAvailability:
      enabled: false
      slotPrefix: _cnp_
    updateInterval: 30
  primaryUpdateMethod: restart
  bootstrap:
    initdb:
      #import:
      #  schemaOnly: false
  failoverDelay: 0
  maxSyncReplicas: 0
  switchoverDelay: 40000000
  storage:
    resizeInUseVolumes: true
    size: 1Gi
  walStorage:
    resizeInUseVolumes: true
    size: 1Gi
  primaryUpdateStrategy: unsupervised
  instances: 3
  imageName: 'quay.io/enterprisedb/edb-postgres-advanced:15.1'
  licenseKey: 'FT7YCAYBAEDUY2LDMVXHGZIB76BAAAIDAECEIYLUMEAQUAABAFJAD74EAAAQCUYB76CAAAAABL7YGBIBAL7YMAAAAD7ACTP7QIA77YL3EJRXK43UN5WWK4RCHIRHGZLSM5UW6LTSN5WWK4TBIBSW45DFOJYHE2LTMVSGELTDN5WSELBCNZQW2ZJCHIRGG3DVON2GK4RNONQW24DMMUWXIZDFEIWCE3TBNVSXG4DBMNSSEORCN5YGK3TTNBUWM5BNN5YGK4TBORXXE4ZCFQRGS3TTORQW4Y3FOMRDUMZMEJYHE33EOVRXIIR2EJRWY33VMQWW4YLUNF3GKLLQN5ZXIZ3SMVZXC3BCFQRGK6DQNFZHSX3EMF2GKIR2EIZDAMRUFUYDGLJSGJKDAMB2GAYDUMBQLIRCYITNMV2GCZDBORQSEOT3EJUXGX3UOJUWC3BCHIRHI4TVMURH27IBGEBBET2XWDGGVU74OGFDZ7K6AIXWL2CXQVETCIJJDEFM3NEFXPPPQTFT6EZAIXKSFBYD2YW63LZYI3JLAEYQFV7LWQYNJFOFH46FOY5FJMN5JIPKPUSM2CY26667NRL5ZDHOZUQUXSTIB7DN4GYMVZKH7BMQTSEP6EAA===='

  postgresql:
    epas:
      tde:
        enabled: true
        secretKeyRef:
          name: tde-key
          key: key
        #wrapCommand:
        #  name: tde-wrap-command
        #  key: openssl enc -aes-128-cbc -pass pass:temp-pass -e -out %p
        #unwrapCommand:
        #  name: tde-unwrap-command
        #  key: openssl enc -aes-128-cbc -pass pass:temp-pass -d -in %p

  bootstrap:
    initdb:
      redwood: true

  minSyncReplicas: 1
  maxSyncReplicas: 1
