apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-sample-17
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  enableSuperuserAccess: true

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      import:
        type: microservice
        databases:
          - postgres
        source:
          externalCluster: cluster-sample

  externalClusters:
    - name: cluster-sample
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: cluster-sample-rw
        user: postgres
        dbname: postgres
      password:
        name: cluster-sample-superuser
        key: password

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "512Mi"
      cpu: "1"

  managed:
    services:
      #disabledDefaultServices: ["ro", "r"]
      additional:
      - selectorType: rw
        serviceTemplate:
          metadata:
            name: cluster-sample-17-rw-lb
          spec:
            type: LoadBalancer

