apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-restore
spec:
  instances: 1
  imageName: quay.io/enterprisedb/postgresql:16.4

  storage:
    size: 1Gi

  walStorage:
    resizeInUseVolumes: true
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  bootstrap:
    recovery:
      backup:
        name: backup-test
